import { useState } from "react";
import { Download, Search } from "lucide-react";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { Badge } from "../../../components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../../components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "../../../components/ui/card";
import { Pagination } from "../../../components/Pagination";

interface Report {
  id: string;
  title: string;
  type: "sales" | "inventory" | "users" | "farms";
  generatedBy: string;
  date: string;
  status: "completed" | "processing" | "failed";
  size: string;
}

export function ReportList() {
  const [searchQuery, setSearchQuery] = useState("");

  const reports: Report[] = [
    {
      id: "R001",
      title: "Monthly Sales Report - October 2025",
      type: "sales",
      generatedBy: "System",
      date: "Oct 13, 2025",
      status: "completed",
      size: "2.4 MB",
    },
    {
      id: "R002",
      title: "User Activity Analysis Q3 2025",
      type: "users",
      generatedBy: "Admin",
      date: "Oct 12, 2025",
      status: "completed",
      size: "1.8 MB",
    },
    {
      id: "R003",
      title: "Inventory Stock Report",
      type: "inventory",
      generatedBy: "System",
      date: "Oct 14, 2025",
      status: "processing",
      size: "-",
    },
    {
      id: "R004",
      title: "Farm Performance Summary",
      type: "farms",
      generatedBy: "Admin",
      date: "Oct 11, 2025",
      status: "completed",
      size: "3.2 MB",
    },
    {
      id: "R005",
      title: "Weekly Sales Analysis",
      type: "sales",
      generatedBy: "System",
      date: "Oct 10, 2025",
      status: "completed",
      size: "1.1 MB",
    },
    {
      id: "R006",
      title: "New User Registration Report",
      type: "users",
      generatedBy: "System",
      date: "Oct 9, 2025",
      status: "completed",
      size: "892 KB",
    },
    {
      id: "R007",
      title: "Product Demand Forecast",
      type: "inventory",
      generatedBy: "Admin",
      date: "Oct 8, 2025",
      status: "failed",
      size: "-",
    },
    {
      id: "R008",
      title: "Farm Certification Status",
      type: "farms",
      generatedBy: "System",
      date: "Oct 7, 2025",
      status: "completed",
      size: "1.5 MB",
    },
  ];

  const filteredReports = reports.filter(
    (report) =>
      report.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.type.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const getTypeColor = (type: Report["type"]) => {
    switch (type) {
      case "sales":
        return "bg-green-100 text-green-700";
      case "inventory":
        return "bg-blue-100 text-blue-700";
      case "users":
        return "bg-purple-100 text-purple-700";
      case "farms":
        return "bg-orange-100 text-orange-700";
    }
  };

  const getStatusColor = (status: Report["status"]) => {
    switch (status) {
      case "completed":
        return "bg-green-100 text-green-700";
      case "processing":
        return "bg-yellow-100 text-yellow-700";
      case "failed":
        return "bg-red-100 text-red-700";
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Reports</CardTitle>
            <p className="text-sm text-muted-foreground mt-1">
              View and download system reports
            </p>
          </div>
          <div className="relative w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search reports..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9"
            />
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report ID</TableHead>
                <TableHead>Title</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Size</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredReports.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center py-8">
                    No reports found
                  </TableCell>
                </TableRow>
              ) : (
                filteredReports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-mono text-sm">{report.id}</TableCell>
                    <TableCell className="max-w-xs">{report.title}</TableCell>
                    <TableCell>
                      <Badge variant="secondary" className={getTypeColor(report.type)}>
                        {report.type}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {report.generatedBy}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {report.date}
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className={getStatusColor(report.status)}>
                        {report.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {report.size}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="sm"
                        disabled={report.status !== "completed"}
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Download
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
        <div className="mt-4 text-sm text-muted-foreground">
          Showing {filteredReports.length} of {reports.length} reports
        </div>
      </CardContent>
    </Card>
  );
}
